#!/bin/bash

# Redis server start/stop utility

## Author: Zvi Avraham <zvi AT zadata DOT com>
## Copyright: 2012-2014 ZADATA Ltd. All Rights Reserved.

if [[ $# < 1 ]] || ([[ $1 != "start" ]] && [[ $1 != "stop" ]])
then
    echo "USAGE: "
    echo "      redis start [port]"
    echo "      redis stop"
    echo ""
    exit 1
fi

REDIS_PORT_DEFAULT=6379

REDIS_CONF="./redis.conf"
REDIS_PID="./redis.pid"

if [[ $1 == "start" ]]
then
    if [[ "x$2" != "x" ]]
    then
        REDIS_PORT=$2
    else
        REDIS_PORT=${REDIS_PORT_DEFAULT}
    fi
    echo "daemonize yes"        >  ${REDIS_CONF}
    echo "port $REDIS_PORT"     >> ${REDIS_CONF}
    echo "pidfile $REDIS_PID"   >> ${REDIS_CONF}

    redis-server ${REDIS_CONF}

    echo ""
    echo "Connect to redis instance using:"
    if [[ ${REDIS_PORT} == ${REDIS_PORT_DEFAULT} ]]
    then
        echo "    redis-cli -h 127.0.0.1"
    else
        echo "    redis-cli -h 127.0.0.1 -p ${REDIS_PORT}"
    fi
    echo ""
elif [[ $1 == "stop" ]]
then
    kill -9 `cat ${REDIS_PID}`
    rm $REDIS_CONF ${REDIS_PID}
else
    echo "Unknown command: $1"
    exit 1
fi
